"""empty message

Revision ID: 0aab2a1c4b57
Revises: c7ea6f46a46d
Create Date: 2019-02-14 07:53:27.732804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aab2a1c4b57'
down_revision = 'c7ea6f46a46d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pitch_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('downvotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('downvote', sa.Integer(), nullable=True),
    sa.Column('pitch_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upvotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upvote', sa.Integer(), nullable=True),
    sa.Column('pitch_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pitches', sa.Column('category', sa.String(length=255), nullable=False))
    op.add_column('pitches', sa.Column('description', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('pitches', sa.Column('title', sa.String(), nullable=True))
    op.create_index(op.f('ix_pitches_description'), 'pitches', ['description'], unique=False)
    op.create_foreign_key(None, 'pitches', 'users', ['owner_id'], ['id'])
    op.drop_column('pitches', 'business')
    op.drop_column('pitches', 'product')
    op.drop_column('pitches', 'interview')
    op.drop_column('pitches', 'sales')
    op.drop_column('pitches', 'funds')
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint('users_pitches_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'password')
    op.drop_column('users', 'pitches_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pitches_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_foreign_key('users_pitches_id_fkey', 'users', 'pitches', ['pitches_id'], ['id'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'pass_secure')
    op.drop_column('users', 'bio')
    op.add_column('pitches', sa.Column('funds', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('sales', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('interview', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('product', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('business', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_index(op.f('ix_pitches_description'), table_name='pitches')
    op.drop_column('pitches', 'title')
    op.drop_column('pitches', 'owner_id')
    op.drop_column('pitches', 'description')
    op.drop_column('pitches', 'category')
    op.drop_table('upvotes')
    op.drop_table('downvotes')
    op.drop_table('comments')
    # ### end Alembic commands ###
